"""Shared constants for the L2D config editor."""

CSV_COLUMNS = [
    "id",
    "desc",
    "memo",
    "ship_skin_id",
    "draw_able_name",
    "parameter",
    "mode",
    "start_value",
    "range",
    "parts_data",
    "ignore_react",
    "react_condition",
    "ignore_action",
    "range_abs",
    "drag_direct",
    "react_pos_x",
    "react_pos_y",
    "offset_circle",
    "offset_x",
    "offset_y",
    "smooth",
    "revert_smooth",
    "revert",
    "save_parameter",
    "revert_action_index",
    "revert_idle_index",
    "gyro",
    "gyro_x",
    "gyro_y",
    "gyro_z",
    "limit_time",
    "listener_data",
    "action_trigger",
    "action_trigger_active",
    "shop_action",
    "relation_parameter",
]

ACTION_TRIGGER_IGNORE = (
    "main_1",
    "main_2",
    "main_3",
    "main_4",
    "mission",
    "mission_complete",
    "complete",
    "login",
    "home",
    "mail",
    "touch_body",
    "touch_head",
)

FUNCTION_NODE_TYPES = ("TouchIdle", "TouchDrag")
CLIPBOARD_MIME = "application/x-l2d-node-json"
